export const FETCH_HABITS_SUCCESS = 'FETCH_HABITS_SUCCESS';
export const FETCH_HABITS_FAILURE = 'FETCH_HABITS_FAILURE';
export const FETCH_HABITS_REQUEST = 'FETCH_HABITS_REQUEST';
export const SHOW_INPUT = 'SHOW_INPUT';
export const FETCH_HABITS = 'FETCH_HABITS';
export const REMOVE_HABIT = 'REMOVE_HABIT';
export const MAKE_EDIT_HABIT = 'MAKE_EDIT_HABIT';